FROM php:5.6-apache

RUN apt-get update && apt-get upgrade -y \
    && docker-php-ext-install pdo_mysql

RUN a2enmod php5 rewrite

#Configure vhost
ADD ./apache-config.conf /etc/apache2/sites-available/000-wordpress.conf
RUN ln -s /etc/apache2/sites-available/000-wordpress.conf /etc/apache2/sites-enabled/000-wordpress.conf

EXPOSE 80

# By default, simply start apache.
CMD /usr/sbin/apache2ctl -D FOREGROUND
